/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jetclicker;

//import java.util.LinkedList;
//import java.util.Queue;

public class App {


    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Fenetre tab = new Fenetre();
        tab.setVisible(false); //pour actualiser la fenetre et avoir les limite de l'écran actualisé (c'est du bricolage)
        tab.setVisible(true);

        Thread Tick = new Thread(new Tick());
        Tick.start();


        //Queue<explosion> queue = new LinkedList<>();
        
        //queue.add(new explosion(2,1));
        //queue.add(new explosion(6,4));

        //explosion one = queue.peek();

        //System.out.println(one.showPosition());

        //queue.remove();
    }
}
